### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/CommandLineParser

### ISSUE THREAD

**Issue by safalabolo** [kraftek/awsdownload#1]
Dear Kraftek,
I followed the steps indicated
but you get the following error message:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/CommandLineParser
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
    at java.lang.Class.getMethod0(Class.java:3018)
    at java.lang.Class.getMethod(Class.java:1784)
    at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.CommandLineParser
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)

I can not find the solution.
Thanks in advance for your reply

**Comment by kraftek** [comment]
There was one step missing from description.
You should run the assembly plugin before actually using the packaged jar, since the maven package goal doesn't bring the necessary dependencies.
After packaging, please run "mvn assembly:assembly" or "mvn assembly:single".
Then, in the target folder, you should find a directory named "S2ProductDownloader-1.0-bin\S2ProductDownloader-1.0". The jar should be run from within this directory.

**Comment by safalabolo** [comment]
Dear kraftek,
thanks for your reply and your support.
All the best

**Comment by safalabolo** [comment]
Dear kraftek,
Currently downloading from AWS and ESA-HUB is successful.
Unfortunately, the processing by SEN2COR granule SEN2COR downloaded fails, contrary to what happens for the same granule selected from the entire acquisition (zip file) downloaded via a simple download manager.

A first warning is the message when downloading: "Metadata (name products) Does not contain one or more angles grids!"

Thanks in advance for your reply
